### ISSUE TITLE
PGNs 65001...65030: AC Power

### ISSUE THREAD

**Issue by tkurki** [SignalK/n2k-signalk#16]
65005: Utility Total AC Energy
{"timestamp":"2015-01-15-16:25:15.858","prio":"3","src":"192","dst":"255","pgn":"65005","description":"Utility Total AC Energy","fields":{"Total Energy Export":"5425","Total Energy Import":"0"}}

65012: Utility Phase A AC Reactive Power
{"timestamp":"2015-01-15-16:25:15.852","prio":"3","src":"192","dst":"255","pgn":"65012","description":"Utility Phase A AC Reactive Power","fields":{"Reactive Power":"191","Power Factor Lagging":"Lagging"}}

65013: Utility Phase A AC Power
{"timestamp":"2015-01-15-16:25:12.753","prio":"3","src":"192","dst":"255","pgn":"65013","description":"Utility Phase A AC Power","fields":{"Real Power":"1433","Apparent Power":"1439"}}

65014: Utility Phase A Basic AC Quantities
{"timestamp":"2015-01-15-16:25:15.870","prio":"3","src":"192","dst":"255","pgn":"65014","description":"Utility Phase A Basic AC Quantities","fields":{"Line-Line AC RMS Voltage":"117","Line-Neutral AC RMS Voltage":"117","AC RMS Current":"12"}}

65015: Utility Total AC Reactive Power
{"timestamp":"2015-01-15-16:25:15.892","prio":"3","src":"192","dst":"255","pgn":"65015","description":"Utility Total AC Reactive Power","fields":{"Reactive Power":"191","Power Factor Lagging":"Lagging"}}

65016: Utility Total AC Power
{"timestamp":"2015-01-15-16:15:20.210","prio":"3","src":"192","dst":"255","pgn":"65016","description":"Utility Total AC Power","fields":{"Real Power":"1239","Apparent Power":"1239"}}

65017: Utility Average Basic AC Quantities
{"timestamp":"2015-01-15-16:25:15.657","prio":"3","src":"192","dst":"255","pgn":"65017","description":"Utility Average Basic AC Quantities","fields":{"Line-Line AC RMS Voltage":"117","Line-Neutral AC RMS Voltage":"117","AC RMS Current":"12"}}

**Comment by timmathews** [comment]
This Gist is a partial Signal K tree covering all of the PGNs from 65001 - 65030. I will turn this into JSON-schema today

https://gist.github.com/timmathews/91976d0a6c114f971f22

**Comment by fabdrol** [comment]
I've started writing a parser for an AC system based on a real-world use case, but I'm running into problems that (I think) may be problematic about our data model (and NMEA2000's). Or I may be misunderstanding how to use it.

> In my particular use case, the vessel has three possible sources of AC power: shore/utility, a generator and a DC->AC inverter. Only one of these is on at any given time, and these are muxed. There is a single Maretron ACM100UM that measures the AC power, regardless of the source. That means that (A) the "source" is something generic like `line`, as we don't know what source the power is actually coming from. The power is single-phased, and only Line-line RMS V, Line-neutral RMS V, frequency and current are measured. This doesn't seem to be an unusual use case to me (but then, what do I know?), and whilst it's easy to write a parser specifically for this use case, I'm having trouble coming up with how that parser could be written so generically that it can be used by any Joe Boater.

1. As far as I can tell, there is no way to get the name or instance (i.e. `<RegExp>` part of the key) from the PGN so if there are more than one of a single kind of device (e.g. multiple generators for different parts of the vessel) there's a problem. It also raises the question of what to parse as the <RegEx> - the CAN bus source address (which changes)?
3. If there AC source has a single phase, the specification prescribes using a path of `electrical/ac/<RegExp>/phase/single/(...)`. How do we know if there is only a single source, when parsing the `Average Basic AC Quantities` PGNs? E.g. 65017, 65004. 

@timmathews I believe you wrote most of the electrical schema, what are your thoughts on this? This discussion may belong in the schema repo, if the model is flawed indeed (and not my understanding of it - I'm no AC expert).

**Comment by fabdrol** [comment]
Initial work on AC:
- https://github.com/decipherindustries/n2k-signalk/blob/ac-power/pgns/65004.js
- https://github.com/decipherindustries/n2k-signalk/blob/ac-power/pgns/65017.js

**Comment by fabdrol** [comment]
ping @tkurki @timmathews

**Comment by timmathews** [comment]
### Regarding point 1
Unfortunately, the J1939 PGNs are difficult to deal with and where IMO, NMEA 2000 made some good improvements. Unlike most of the n2k PGNs which have an instance field, these rely on the recipient maintaining a NAME database and why I've argued (and lost) for years now that knowing the CAN bus source address is not enough. We need to keep track of the only guaranteed static ID for a device which is the first 21(or 32 if you include the manufacturer ID) bits of the ISO Address Claim PGN (aka the NAME field).

So, basically the `getACLineId` function needs to be able to take the current CAN bus source address and look up the device's NAME value. Then this can be used to get (if we want) a friendly, user-specified name like `bus1` or `starboardGenerator`. Otherwise the path will be something like `electrical.ac.0x123ABC.phaseA.lineNeutralVoltage`, which is fine and guaranteed to refer to the same device each time, but not all that informative.

### Regarding point 2
The 650xx PGNs follow a pretty logical organization. I suspect they were made early in the standardization process before the standards committees got more stingy with numbers, but I don't know. Basically, there are three categories, `bus`, `utility`, and `generator`. In my initial gist, I included those as well, but I think in the current schema definition those have been replaced with a generic regex. Then under those are a PGN or set of PGNs for the source as a whole and another set of PGNs which break those values down by phase.

**Warning, conjecture ahead** A single phase device should be easy to identify because it won't send any of the phase-specific PGNs, only the "rollup" PGNs. So, for example a single phase monitoring device will likely send just 65004, whereas a polyphase monitoring device will send 65001-65003 in addition to 65004. Likewise, a device which knows that it's a generator would send 65018, 65028, 65029, and 65030; but not 65019-65027 unless it was a 3-phase device.

Unfortunately, it's also possible that a single phase device (or a monitoring device capable of polyphase monitoring, but only using one phase) might also populate one of the sets of phase-specific PGNs. If that's the case, there is no way to tell the difference between a single phase device and a 3-phase device with two phases disconnected. Of course the user will know and can just choose to ignore the data under the phase branch.

**Comment by fabdrol** [comment]
P.s., regarding naming in N2K: I believe you get problems with devices that don't provide an option to set a name, if you have two of the same make and type on the network. E.g. you'll do an ISO address lookup, and find that you have two GPSs of the same type and make; how will you know which one is which? One could unplug one, record the src address for the first; plug the second one in and record the src address for the second. However, as far as I can remember, those src addresses are not guaranteed to remain the same (if a new device is added, all src address are renegotiated on the bus)

**Comment by timmathews** [comment]
Concerning your Maretron ACM100 install, I think the way you're using it is probably the _most common_ way it's used: connected  downstream of the source selector switch. In the case of a single phase boat, the factory default configuration should work just fine. According to the manual, it only ships with the "average value" PGNs enabled (65004, '17, and '29) for voltage and current.

The problem isn't in your usage, but rather the electrical schema. The paths shouldn't be:

```
electrical.ac.<device>.phase.single.*
electrical.ac.<device>.phase.a.*
electrical.ac.<device>.phase.b.*
electrical.ac.<device>.phase.c.*
```

they should be

```
electrical.ac.<device>.*
electrical.ac.<device>.phaseA.*
electrical.ac.<device>.phaseB.*
electrical.ac.<device>.phaseC.*
```

The `phase` value groups should be thought of as "debugging" information. In a 3-phase system most of the time you only care about the "average" voltage and current. It's only when a phase starts to sag or the load between phases is grossly unbalanced or if you suspect trouble with a piece of equipment (e.g. a burned out winding in a 3-phase motor) that you would actually care about the individual phase values.

In the current schema, there is no place for this "average" data, except in `electrical.ac.<device>.phase.single.*` which doesn't really make sense.

**Comment by timmathews** [comment]
> The problem is that the parsers themself don't have any "native" way of accessing the CAN bus.

I don't think they need to. Either the server maintains the NAME database and the parser queries it or, as you said, we modify the CANboat code (both C and JS versions) to include the source device's name in their output. I think I prefer the second option.

```
{
  timestamp": "2014-08-15T19:00:00.045",
  "prio": 3,
  "src": 160,
  "dst": 255,
  "name": 32199900, // New Field
  "pgn": 129033,
  "description": "Time & Date",
  "fields": {"Date":"2014.08.15", "Time": "18:59:59.04620","Local Offset":180}
}
```

The device's NAME (I'm not capitalizing for emphasis, that's how it's rendered by the J1939 spec) is not something the end user sets. It's essentially a serial number programed by the factory, like an Ethernet MAC address. This is how you can differentiate between two otherwise identical devices.

Source addresses are necessary for sending data to a device, but we must not assume them to be static and we shouldn't even expose them to the end user. In order to be compliant with the n2k spec, we must maintain a lookup table between NAME and current address for every device on the network. This should be accessible to the end user somehow.

-----
- NAME == MAC Address (Layer 2)
- Source Address == IP Address (Layer 3)
- ISO Address Claim negotiation == [Link local address assignment](https://en.wikipedia.org/wiki/Link-local_address)

**Comment by tkurki** [comment]
I just recently deleted the github server branch `canname` that had work towards NAME-src mapping. If you happen to have that branch please repush. I can do that later as well.

**Comment by tkurki** [comment]
https://github.com/SignalK/signalk-server-node/tree/canname

**Comment by sbender9** [comment]
The probably needs one more addition. It should send out a ISO Request(59904) for 60928, that will make everything on the network announce themselves.

**Comment by sbender9** [comment]
Also would need moved to n2k-signalk since the info is needed to compute the path

**Comment by fabdrol** [comment]
@sbender9 @tkurki I feel more for @timmathews proposal of adding it to canboat(js), as that keeps the data flow one-way (`canboat -> n2k-signalk -> server -> client`). What do you guys think?

**Comment by tkurki** [comment]
I started it within server because it needs to be active on the bus, but n2k-signalk or canboatjs suits me fine. I believe this should tie into source/$source as well.

**Comment by timmathews** [comment]
I updated the title of this issue because if we sort out 65005...65017, we get 65001...65004 and 65018...65030 basically for free (bus and generator PGNs).

**Comment by jncarter123** [comment]
I may be oversimplifying things here but I don't think we need the NAME to identify the source. We just need the device instance provided in the 60928 ISO address claim and is stored in sources. For example i have 3 of the ACM100s. One for utility (utility instance 0), one for the generator (generator instance 0), and one for the inverter (utility instance 1). Then the paths would look like 
electrical.ac.<device>.<instance>.*
electrical.ac.<device>.<instance>.phaseA.*
electrical.ac.<device>.<instance>.phaseB.*
electrical.ac.<device>.<instance>.phaseC.*
electrical.ac.<device>.<instance>.average.*
where device is utility, bus, or generator based on the received PGN.

So my paths would look like
electrical.ac.utility.0.average.*
electrical.ac.utility.0.phaseA.*
electrical.ac.utility.0.phaseB.*
electrical.ac.generator.0.average.*
electrical.ac.generator.0.phaseA.*
electrical.ac.utility.1.average.*
electrical.ac.utility.1.phaseA.*

Open to feedback and suggestions and would love to help move this forward how I can. Thanks!

**Comment by sbender9** [comment]
Here's a first try at these #177 

The use `instance` 0 for now, but I will be adding `NAME` to canboatjs and then we can use that instead.

**Comment by fabdrol** [comment]
@sbender9
