### ISSUE TITLE
callsignVhf missing for 129794 and 129810

### ISSUE THREAD

**Issue by wellenvogel** [SignalK/n2k-signalk#237]
The decoder should set communication/callsignVhf from the mentioned PGNs. Otherwise AIS data from N2K will miss this information (although available in the bus data).

**Comment by pa1pdr** [comment]
Can I ask for merging this? I also need the callsignVHF to be populated in the SK delta's

**Comment by sbender9** [comment]
please check the PR, I added a comment

**Comment by wellenvogel** [comment]
Unfortunately I currently do not have any idea about the signalK testing - so it's hard for me to add those tests.

**Comment by pa1pdr** [comment]
Andreas, if you go into the test directory, you'll find e.g. the 129794_ais_class_a_static_data.js file and add somewhere at line 81 the line 
```
tree.should.have.nested.property(
      'communication.callsignVhf',
      '3FJJ4'
    )
```
The 3FJJ4 is in the testdata in line 46. 
Since the expected IMO number in line 69  is wrong, the test will fail anyway, but that is not your issue..

Do something similar for 129810 and you're done. Thanks for your help!

**Comment by wellenvogel** [comment]
Thanks. Added the test for 129794. But currently there is no test for 129810 at all.
